### ISSUE TITLE
Porting immediatelyRender and shouldRerenderOnTransaction from tiptap?

### ISSUE THREAD

**Issue by sradu** [TypeCellOS/BlockNote#1027]
tiptap added a couple of improvements that make everything faster with react views: https://tiptap.dev/blog/release-notes/say-hello-to-tiptap-2-5-our-most-performant-editor-yet.

I can see they are implemented in their useEditor, and blocknote has its own version.

Would it be possible to sync the two versions together so we have the performance improvements?

**Comment by YousefED** [comment]
I don't think these are relevant for BlockNote. We have previously (partially) replaced the TipTap React integration because the react integration of TipTap was lacking, partially because of performance reasons. It's nice to see TipTap addressing some.

Specifically looking at their changes:

- BlockNote's mounting system already uses a similar approach as `immediatelyRender` (it doesn't delay rendering)
- shouldRerenderOnTransaction is not relevant as we don't use `useEditor`
