### ISSUE TITLE
CodeBlock support

### ISSUE THREAD

**Issue by yujinqiu** [TypeCellOS/BlockNote#147]
It's really useful to support code block.

**Comment by apaarsinha** [comment]
Curious to know if we can implement our own custom block currently in 0.5.1.

**Comment by npearson72** [comment]
🦗

**Comment by NLaundry** [comment]
Would definitely love to see this happen as well. I'm using BlockNote for a research project at UofT and it would be super valuable to have this feature.

**Comment by trancethehuman** [comment]
Was evaluating between this and Yoopta - blocknote is way more stable but doesn't have codeblocks out of the box. It'd be insanely good if it does!

**Comment by YousefED** [comment]
> Was evaluating between this and Yoopta - blocknote is way more stable but doesn't have codeblocks out of the box. It'd be insanely good if it does!

Cool, what are you building? We'll aim to add the codeblock next two weeks, it's been overdue for a while :)

**Comment by trancethehuman** [comment]
A devrel tool for Supabase and a few other folks!

It'd be awesome to be able to support Python, JS/TS, Go, Bash and the other common highlight types. Tabbing, being able to paste into Blocknote a markdown code snippet or HTML and turn into codeblock instantly would be amazing.

I can switch over easily since our data model is based on Slate and I still have my blocknote implementation.

**Comment by YousefED** [comment]
sounds interesting, really like supabase! Would love to learn more, just
connected on linkedin :)

**Comment by JaeungJayJang** [comment]
Glad to check this out and hear that the feature will be released soon!
Looking forward to see the implementation :)
