### ISSUE TITLE
Why Block?

### ISSUE THREAD

**Issue by linzhefeng** [TypeCellOS/BlockNote#150]
Hello! I am very interested in editors and Blocknote, and I would love to learn more about the design philosophy behind Blocknote. I am particularly curious about the importance of the "block" concept and its indispensable role.

As an example, let's say I want to add color to some content. Without the "block" concept, I could potentially set the color directly on the parent element and achieve the same effect. However, I am interested in learning why the "block" concept is considered important and what benefits it provides in terms of design and functionality.

**Comment by YousefED** [comment]
@linzhefeng part of this is described here: https://www.blocknotejs.org/docs/introduction

And there are some more reasons I can think of:

- **Programmability**: The Block-structure helps with programmability. Without Blocks, interfacing with the document from code is quite difficult, because there’s no clear schema. BlockNote makes this a lot easier (see https://www.blocknotejs.org/docs/blocks)
- **Encourage nice structure for users**: In non-block editors, users can create quite messy documents. BlockNote’s clear block-based structure encourages well-structured, clean and “semantic” documents.
- **Modern UX**: It's also a UX decision. Modern products like Notion, Coda, Microsoft Loop are setting a new standard for what users expect from modern text editors with blocks. With blocks, we can add easy dragging, but potentially also features like sharing blocks across documents, etc.
