### ISSUE TITLE
Consider rendering menus within editor DOM

### ISSUE THREAD

**Issue by YousefED** [TypeCellOS/BlockNote#172]
We currently append them to body. We should consider to position them within the dom of the editor. This could fix some manual-position issues like:

https://github.com/TypeCellOS/BlockNote/pull/167#pullrequestreview-1389313648

**Comment by YousefED** [comment]
Possible related: https://github.com/TypeCellOS/BlockNote/issues/189

**Comment by matthewlipski** [comment]
Some findings from looking into this issue:
- TipTap extensions get initialized before the editor itself, so the `.ProseMirror` element we'd want to attach a menu to doesn't exist when we need to create the factory for it. Could just attach to a parent instead, not sure what the best solution is atm.
- In React, the editor is rendered from `#root`, which means that for any children, we can't really attach another root to render the menus. We would have to pass the menus down to `BlockNoteView` and have that sort out the rendering. This would require quite a lot of changes because showing/updating/hiding the menus is currently the responsibility of the corresponding PM plugins, but now `BlockNoteView` would be responsible for it.
