### ISSUE TITLE
Column Layout Request

### ISSUE THREAD

**Issue by jiawei686** [TypeCellOS/BlockNote#350]
**Is your feature request related to a problem? Please describe.**
We think Blocknote is amazing and about to use blocknote to build some part of project. Is it possible for us to add a column layout in blocknote. 

<img width="586" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/12953093/a599ec5d-2fef-48ec-924c-651c940f9760">

**Comment by matthewlipski** [comment]
Hmm, depending on how you want the columns to work this can be either very easy or very difficult.

If you just want each block to be displayed as e.g. 2 columns, you can just do this:
```ts
const editor = useBlockNote({
    domAttributes: {
      blockContent: {
        style: "columns: 2",
      },
    },
  });
```
Instead of `style` you can add a CSS class, and use different selectors to only apply the column styling to the blocks you want (e.g. paragraphs).

Alternatively, you can create a custom block (see https://www.blocknotejs.org/docs/block-types#custom-block-types) which has the column styling baked in.

If you want the whole editor to have columns, meaning blocks can be side-by-side, I don't think that's possible atm since it will likely break things like drag and drop.

**Comment by jiawei686** [comment]
Our product needs notion-like column layout, which means I have to implement side-by-side blocks. This is blowing my mind. I'm figuring out is it possible to implement this by using custom blocks. 

<img width="557" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/12953093/07f8dcc1-4554-4c1a-8b55-219b456180aa">

<img width="904" alt="image" src="https://github.com/TypeCellOS/BlockNote/assets/12953093/ed2fda20-5bee-4abe-a78b-4af10f30207d">

**Comment by charanjit-singh** [comment]
@jiawei686 did you manage to implement it?

**Comment by rakesh-eltropy** [comment]
@jiawei686 did you manage to implement it?
@YousefED Any plan to add this in the core editor?

**Comment by YousefED** [comment]
Thanks for showing your interest. This will be a significant feature to add. We'd love to do so, but will require a dedicated sponsor or [bounties](https://console.algora.io/org/BlockNote/bounties/community) to be able to allocate time for this.
