### ISSUE TITLE
Meaningless formatting toolbar for custom blocks in 0.9.4

### ISSUE THREAD

**Issue by marsee339** [TypeCellOS/BlockNote#360]
**Describe the bug**
After updating to 0.9.4, the formatting toolbar started working for custom blocks, but it causes bugs for blocks without InlineContent. Need the ability to disable the toolbar for custom blocks, or at least not display them when they are empty (last screenshot)

**To Reproduce**
If you create a custom block with some content without using InlineContent:

> export const TestBlock = createReactBlockSpec({
>   type: "test",
>   propSchema: {    
>   },
>   containsInlineContent: false,
>   render: (props) =>
>   {
>     return "Some text";
>   }
> });

And after you click on that block in the editor, a meaningless toolbar will appear
![image](https://github.com/TypeCellOS/BlockNote/assets/57190250/4b5df6fd-358b-450d-aa38-1c45ff5acb85)
My implementation uses a custom toolbar, and there are no nesting buttons, so it looks like this.
![image](https://github.com/TypeCellOS/BlockNote/assets/57190250/d73354ce-e358-4e5b-8b9b-b1a3b82e2108)

**Comment by matthewlipski** [comment]
This is is actually mostly intentional behaviour for the most part. The formatting toolbar is effectively made up of three pieces:

Plugin - Figures out when to show the formatting toolbar (basically whenever the editor is focused and something in it is selected) and the bounding box for the selected content. It emits an event whenever it should be shown/hidden or when the bounding box changes.
Positioner - Listens to events from the plugin and actually handles showing/hiding as well as positioning the toolbar.
Element - The React component that actually gets displayed as the toolbar.

So the issue here is not that the plugin is doing something wrong, since it doesn't handle showing/hiding the toolbar. That's the job of the positioner. This is relevant since you can replace the default positioner with your own one that prevents the toolbar from opening in certain blocks. You can pretty much just copy the default [`FormattingToolbarPositioner`](https://github.com/TypeCellOS/BlockNote/blob/main/packages/react/src/FormattingToolbar/components/FormattingToolbarPositioner.tsx) component and add some additional logic for when to call `setShow` to accomplish this.

Lmk if you need any help with this since there's not a lot of documentation on custom positioners atm

**Comment by YousefED** [comment]
@matthewlipski good write up. What do you think would be sensible default behavior for custom blocks (with / without inline content), and would this be easy to implement?

**Comment by kaianuar** [comment]
@matthewlipski I have a checklist custom block that I've implemented like this.

```
export const ChecklistsBlock = createReactBlockSpec({
  type: "checklists",
  propSchema: {
    ...defaultProps,
    checklistTitle: {
      default: "",
    },
    checklistItems: {
      default: "",
    },
    textAlignment: {
      default: "left",
    },
  },
  containsInlineContent: false,
  render: ({ block, editor }) => (
    <ChecklistBlockView
      block={block as SpecificBlock<typeof customSchema, "checklists">}
      editor={editor as BlockNoteEditor<typeof customSchema>}
    />
  ),
});
```

However I'm unable to get the formatting toolbar to appear regardless of whether I set containsInlineContent to `true` or `false`. Is that because the render returns a component rather than just text? Apologies in advance if this is meant to be it's own ticket.

**Comment by marsee339** [comment]
@kaianuar Are you sure you upgraded to 0.9.4? Because I tried your createReactBlockSpec on my custom block (it contains not just text, but many other components) and the toolbar is called. 
And just an observation - textAlignment is already included in defaultProps, there is no point in setting it again

**Comment by matthewlipski** [comment]
> @matthewlipski good write up. What do you think would be sensible default behavior for custom blocks (with / without inline content), and would this be easy to implement?

I think it's fine as-is honestly. This situation will never happen with the default toolbar since it will always at least have the buttons for nesting/unnesting, and I think most custom toolbar implementations also won't encounter this. Probably the best option is just better docs for customizing the positioners.

**Comment by marsee339** [comment]
@matthewlipski I've written a silly WA in a custom FormattingToolbar so far. I'm afraid to take the whole FormattingToolbarPositioner implementation and make my edits to it, because then when I update BlockNote there might be unexpected differences in the implementations. Or do I misunderstand your suggestion to add logic to FormattingToolbarPositioner and I really lack documentation?

**Comment by kaianuar** [comment]
> @kaianuar Are you sure you upgraded to 0.9.4? Because I tried your createReactBlockSpec on my custom block (it contains not just text, but many other components) and the toolbar appeared. And just an observation - textAlignment is already included in defaultProps, there is no point in setting it again

I've got it to appear, but I've had to replace the TextField component that I was using with InlineContent. The only thing though is that for the InlineContent, the onKeyDown event doesn't seem to be working. I need it so that after pressing enter, a new checklist row would be inserted.

So something like this.

```
 <InlineContent
    style={inlineContentStyles}
    onKeyDown={handleKeyPress}
  />
          
  const handleKeyPress = (event: KeyboardEvent<ElementType>) => {
    if (event.key === "Enter") {
      event.preventDefault();

      editor.insertBlocks(
        [
          {
            type: "checklists",
          },
        ],
        editor.getTextCursorPosition().block,
        "after",
      );
    }
  };
```

@matthewlipski Am I even on the right track or should I be doing something different?

**Comment by matthewlipski** [comment]
> > @kaianuar Are you sure you upgraded to 0.9.4? Because I tried your createReactBlockSpec on my custom block (it contains not just text, but many other components) and the toolbar appeared. And just an observation - textAlignment is already included in defaultProps, there is no point in setting it again
> 
> I've got it to appear, but I've had to replace the TextField component that I was using with InlineContent. The only thing though is that for the InlineContent, the onKeyDown event doesn't seem to be working. I need it so that after pressing enter, a new checklist row would be inserted.
> 
> So something like this.
> 
> ```
>  <InlineContent
>     style={inlineContentStyles}
>     onKeyDown={handleKeyPress}
>   />
>           
>   const handleKeyPress = (event: KeyboardEvent<ElementType>) => {
>     if (event.key === "Enter") {
>       event.preventDefault();
> 
>       editor.insertBlocks(
>         [
>           {
>             type: "checklists",
>           },
>         ],
>         editor.getTextCursorPosition().block,
>         "after",
>       );
>     }
>   };
> ```
> 
> @matthewlipski Am I even on the right track or should I be doing something different?

Yep this should indeed be the right way of doing it, the Formatting Toolbar requires an `InlineContent` component to show up. Not sure why the event handler isn't working, event must be getting handled somewhere further up. Can you change it to an `onKeyDownCapture` event and see if it fixes it?

**Comment by matthewlipski** [comment]
> @matthewlipski I've written a silly WA in a custom FormattingToolbar so far. I'm afraid to take the whole FormattingToolbarPositioner implementation and make my edits to it, because then when I update BlockNote there might be unexpected differences in the implementations. Or do I misunderstand your suggestion to add logic to FormattingToolbarPositioner and I really lack documentation?

Good point about your custom positioner not getting updated if the original implementation changes. While I don't think this is a major issue (your custom positioner will most likely keep working even if the default one changes), I think it's pretty clear that documentation for customizing positioners should be better, so we'll work on that soon👍
