### ISSUE TITLE
Error: Could not find block in the editor with matching ID with Collaboration enabled

### ISSUE THREAD

**Issue by ursnj** [TypeCellOS/BlockNote#366]
**Describe the bug**
When using editor with collaboration replacingBlocks() is throwing this error, but same code is working fine with out collaboration

const editor: any = useBlockNote({
    editable: true,
    theme: theme === THEMES.DARK ? THEMES.DARK : THEMES.LIGHT,
    collaboration: {
      provider,
      fragment: doc.getXmlFragment('document-store'),
      user: {
        name: myName,
        color: 'red'
      }
    }
  } as any);
  
  useEffect(() => {
    if (editor && !isPageLoading) {
      const getBlocks = async () => {
        const initContent = pageData?.uuid ? pageData.details : defaultPage.details;
        const blocks: any = await editor.HTMLToBlocks(initContent);
        editor.replaceBlocks(editor.topLevelBlocks, blocks); // This is causing issue
      };
      getBlocks();
    }
  }, [!!editor, !!pageData]);

Uncaught (in promise) Error: Could not find block in the editor with matching ID.
    at Z (nodeUtil.ts:31:11)
    at xt (blockManipulation.ts:27:35)
    at Qe (blockManipulation.ts:124:3)
    at Qo.replaceBlocks (BlockNoteEditor.ts:576:19)
    at getBlocks (PagesNew.tsx:78:16)
Z @ nodeUtil.ts:31
xt @ blockManipulation.ts:27
Qe @ blockManipulation.ts:124
replaceBlocks @ BlockNoteEditor.ts:576
getBlocks @ PagesNew.tsx:78
await in getBlocks (async)
(anonymous) @ PagesNew.tsx:80
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
performSyncWorkOnRoot @ react-dom.development.js:26076
flushSyncCallbacks @ react-dom.development.js:12042
commitRootImpl @ react-dom.development.js:26959
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 20 more frames
Show less

2BlockNoteEditor.ts:329 Uncaught TypeError: Cannot read properties of null (reading 'id')
    at Qo.getBlock (BlockNoteEditor.ts:329:27)
    at HTMLBodyElement.<anonymous> (SideMenuPlugin.ts:446:28)

**To Reproduce**
<links to a sandbox or clear steps to reproduce are super helpful!>

**Misc**
- Node version: 16.13.2
- Package manager: npm
- Browser: CHROME
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by ursnj** [comment]
@matthewlipski any luck on this ???

**Comment by matthewlipski** [comment]
We've decided to push this back a bit since the fix is pretty involved and we're working on other stuff atm. There are a few things you can try in your code though as workarounds.

Basically the root issue is that the ProseMirror plugin which gives blocks their IDs was causing other issues with collaboration due to some code that ran on editor initialization. This code was removed, and everything still works fine once the doc is fetched by the collaboration plugin. Before that happens, however, the initial blocks in the editor have `null` IDs, causing this error.

There are 2 things you can try:
1. Wait until `editor.topLevelBlocks[0].id !== null`, then replace the content, which should mean the doc has been fetched by the collaboration plugin. This will update the content for everyone collaborating on the document.
2. Set the `initialContent` editor option with the content you want. This should fix the ID issue but not 100% sure whether it will update the content for everyone or if it will get overwritten by the collaboration doc.

**Comment by Elon-Mask12** [comment]
Were you able to figure out something @ursnj ? : (

**Comment by ursnj** [comment]
Unfortunately no @Elon-Mask12 , tried @matthewlipski suggested ways but no luck :(

**Comment by shreeram312** [comment]
@Elon-Mask12 Were you able to figure out
