### ISSUE TITLE
MIT or Apache 2.0 Licensing changes

### ISSUE THREAD

**Issue by sebasjuancho** [TypeCellOS/BlockNote#416]
BlockNote is licensed under MLP-2 but Prosemirror and TipTap are licensed under MIT. The legal department in the company I work for is being reluctant to approve BlockNote use in our project because of this difference. Even though we are not making changes to the code and using it as is, they are particularly troubled by the disclosure requirements this license has, and it has become a blocker.
Would you be open to change licensing to MIT o Apache 2 license?

**Comment by YousefED** [comment]
Hi,

At this moment we think the MPL license is a great fit, because it aims that changes to the project files are being open sourced and thus contribute back to the project.

If you're not making any changes to the code, there should be no issue at all. If this is still a problem for the legal department, feel free to get in touch and perhaps we can arrange a commercial license without the MPL restriction
