### ISSUE TITLE
Issue with Custom BlockTypeDropdown Item Display and Click Event 

### ISSUE THREAD

**Issue by hsingh-ds** [TypeCellOS/BlockNote#473]
I am encountering an issue while attempting to add a custom BlockTypeDropdown item using the provided documentation ([link to documentation](https://www.blocknotejs.org/docs/formatting-toolbar#changing-the-block-type-dropdown)). The problem lies in the fact that the custom item is not being displayed as expected, and I am unable to find a way to handle the click event for this custom item.

**Code Snippet**

`<DefaultFormattingToolbar
  {...props}
  blockTypeDropdownItems={[
    ...defaultBlockTypeDropdownItems,
    {
      name: "Image",
      type: "image",
      props: {
        src: "https://via.placeholder.com/1000",
        alt: "image",
      },
      icon: RiImage2Fill,
      isSelected: (block) => block.type === "image",
    },
  ]}
/>`

**Issues Encountered**
1. Custom Item Not Displayed: The custom BlockTypeDropdown item is not being shown as expected, despite following the documentation.
3. Lack of Click Event Handling: The documentation does not provide information on handling click events for custom BlockTypeDropdown items, and the click event seems to be inaccessible.

**Comment by matthewlipski** [comment]
Ah, yeah I see where the confusion comes from. Prior to implementing the default image block, we made a simple image block for the custom block example with slightly different props. If the dropdown item type and props don't match what's in the schema, it won't show up, which is where the problem lies. This should work instead (just remove the `alt` prop):
```jsx
<BlockNoteView editor={editor}>
  <FormattingToolbarPositioner
    editor={editor}
    formattingToolbar={(props) => (
      <DefaultFormattingToolbar
        {...props}
        blockTypeDropdownItems={[
          ...defaultBlockTypeDropdownItems,
          {
            name: "Image",
            type: "image",
            props: {
              url: "https://via.placeholder.com/1000",
            },
            icon: RiImage2Fill,
            isSelected: (block) => block.type === "image",
          },
        ]}
      />
    )}
  />
</BlockNoteView>
```

As for the `onClick` event, that is indeed hidden as the block type dropdown has preset logic. You can set an `onClick` handler if you create your own dropdown - BlockNote also provides components you can use for this:
[Dropdown](https://github.com/TypeCellOS/BlockNote/blob/main/packages/react/src/components-shared/Toolbar/ToolbarDropdown.tsx)
[Dropdown Target](https://github.com/TypeCellOS/BlockNote/blob/main/packages/react/src/components-shared/Toolbar/ToolbarDropdownTarget.tsx)
[Dropdown Item](https://github.com/TypeCellOS/BlockNote/blob/main/packages/react/src/components-shared/Toolbar/ToolbarDropdownItem.tsx)

Thanks for bringing this up, docs will be updated👍

**Comment by hsingh-ds** [comment]
Thanks @matthewlipski. It worked.

**Comment by hsingh-ds** [comment]
Thanks @matthewlipski. It worked.
