### ISSUE TITLE
In order to add the outline and anchor for the Header blocks, Add the id in the block. 

### ISSUE THREAD

**Issue by CharlieCho2017** [TypeCellOS/BlockNote#478]
**Is your feature request related to a problem? Please describe.**
I want to add the outline and anchor for the Header block. But the block doesn't has the id attribute. Could add ''id" in the block.

**Describe the solution you'd like**
In the block , there is a id attribute. its value is the same as "data-id". It will be helpful for adding anchor.
![image](https://github.com/TypeCellOS/BlockNote/assets/28870006/cf0f9b09-61a5-46b2-8aea-da1c14fe2b77)

**Additional context**
![image](https://github.com/TypeCellOS/BlockNote/assets/28870006/dbe9699f-7fd2-48ff-a333-4d11caffd270)

**Comment by matthewlipski** [comment]
Why not just use the `[data-node-type="blockContainer"][data-id="..."]` selector for this instead?

**Comment by sb8244** [comment]
I came across this as looking to build a table of contents block type. In the outputted HTML of headings `renderHTML` of `HeadingContentBlock`, there are no IDs. This makes it not possible to link to it.

I may be missing something, but there's also not a way to access `block.id` inside of the `renderHTML` function, so I can't add it in my custom version of the heading block either.

**Comment by matthewlipski** [comment]
True, there is no way of getting the ID within `renderHTML`. Though if you're using the [BlockNote API to create a block](https://www.blocknotejs.org/docs/custom-schemas/custom-blocks), this shouldn't be an issue as you get access to the block including its ID in `render`. If you're using `renderHTML` is it because you have an existing TipTap node that you're trying to convert into a BlockNote block?
