### ISSUE TITLE
Support inline code with formattingToolbar.

### ISSUE THREAD

**Issue by CharlieCho2017** [TypeCellOS/BlockNote#510]
**Is your feature request related to a problem? Please describe.**
These is no inline code in the formattingToolbar.

**Describe the solution you'd like**
Could add the inline code in the formattingToolbar? Or how to achieve the feature with custom formatting toolbar?

**Comment by hampak** [comment]
+1 would also love this feature to be implemented

**Comment by matthewlipski** [comment]
You can add a code toggle button to the formatting toolbar by copying the [default one](https://github.com/TypeCellOS/BlockNote/blob/main/packages/react/src/components/FormattingToolbar/DefaultFormattingToolbar.tsx) and adding the `<ToggledStyleButton editor={props.editor} toggledStyle={"code"} />` component to it. You can then replace the default formatting toolbar by following these docs: https://www.blocknotejs.org/docs/ui-elements#replacing-ui-elements.

I think it's a good idea to add an example for this in the docs, since it does take a few steps.

**Comment by CharlieCho2017** [comment]
> does
There are two issues.
1. when click the code button, props  has ben changed. But the selected text don't change style.

2. If initial contents contain inline code, text will be styled. But Inline code doesn't has background color. It only show different font family. Could add the background color for it?
