### ISSUE TITLE
How to dynamically set the initial content?

### ISSUE THREAD

**Issue by mez** [TypeCellOS/BlockNote#568]
I have different tabs on a screen and they are like different pages. What is the best way to initialize the editor with initial content on tab changes? Should I create a new editor instance on different tabs or somehow change the initial content on a single editor instance? How should I go about doing this?

**Comment by matthewlipski** [comment]
I think in this case having an editor instance per tab is the best approach since they're effectively separate pages. If you do only want to use a single editor instance though, that's also possible. You want to keep a store of the editor content for each tab with `editor.topLevelBlocks`, and update that in `onEditorContentChange`. When switching tabs, you then use `editor.replaceBlocks(editor.topLevelBlocks, store[tabId])` to replace the editor content with the content that's saved for that tab.

**Comment by mez** [comment]
Thank you!

**Comment by FasalMohammadh** [comment]
Hi,
```
 useEffect(() => {
    if (data.file?.content) {
    }
  }, [data.file.content, fileId]);
```

i have my fileId comes from useParams() whenever the id changes i want to set the content of the editor with the file json data fetch from the db how can i do that

what i tried
set content to the state and passed that state value in initializing editor with the useCreateBlockNote

removing all blocks and insert inline content had some errors "Blocks with the following IDs could not be found "
