### ISSUE TITLE
Error: mark not found in styleschema link

### ISSUE THREAD

**Issue by moroshko** [TypeCellOS/BlockNote#627]
**Describe the bug**
When link is added, error is shown in the console and link is not highlighted.

<img width="1059" alt="Screenshot 2024-03-08 at 10 40 34 am" src="https://github.com/TypeCellOS/BlockNote/assets/259753/2ff2602a-c8c8-4ec5-a1b5-4d57a2cc0520">

**To Reproduce**
See readme here: https://github.com/moroshko/blocknote-issue

**Misc**
- Node version: 20
- Package manager: bun
- Browser: Chrome
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

**Comment by YousefED** [comment]
Thanks, I was able to reproduce this on the default examples as well. The warning should be removed, we'll look into this. I don't think it causes any end-user errors though

The styling is probably because your Tailwind installation is resetting the styles of all links on your website, you could reset this with CSS

**Comment by moroshko** [comment]
Thanks @YousefED, silly me with the styling, and yes, it would be great to remove the warning!

**Comment by moroshko** [comment]
btw, CMD+K doesn't seem to trigger Create Link.
