### ISSUE TITLE
Table: Cannot read properties of null ChildNodes

### ISSUE THREAD

**Issue by Verickg** [TypeCellOS/BlockNote#830]
When i add a table option then add some column or rows, appear this error
"Cannot Read Properties of null (reading 'childNodes')"

**To Reproduce**
add table option then add some columns or rows, this error appears in blocknotesjs.org playground
![image](https://github.com/TypeCellOS/BlockNote/assets/105474183/bf8687c3-3f67-4cb8-9d4a-bc856fdb3eff)

**Misc**
- BlockNote version: 0.13.4
- Node version: 20.11.0
- Package manager: npm
- Browser:  Chrome, edge

**Comment by Govind783** [comment]
+1 faced this error many times
exact error - TypeError: Cannot read properties of null (reading 'childNodes') 
not sure why has this issue been assigned a low priority label, we rely heavily on blocknote and especially the table component, and every time the user has added a 3/4 columns and he goes onto adding a row the app crashes and gives that error of child nodes
@matthewlipski @YousefED 

also until your team patches the fix is there a quick work-around that you can suggest @matthewlipski @YousefED

**Comment by matthewlipski** [comment]
This may be fixed with #856, though that PR unfortunately will have to introduce breaking changes to old documents in the way tables are represented in the API.
