### ISSUE TITLE
Saving my BlockNote contents into a Database 

### ISSUE THREAD

**Issue by Pokah1** [TypeCellOS/BlockNote#993]
Please I have carefully gone through the Docs and have been able to set up BlockNote Editor in my Next js project, My major issue is grabbing the content and saving it to a database, Supabase precisely. I need help going about it.
Check if this my setup below is okay.

`import { PartialBlock } from "@blocknote/core";`
```
  const handleEditorChange = (blocks: PartialBlock[]) => {
    const contentString = stringify(blocks);
    setContent(contentString);
  `};`
```

This is where i call the Editor below

  <div>
  **<Editor onChange={handleEditorChange} />**
</div>

**Comment by Pokah1** [comment]
Hello, good day.
I appreciate the response.
please I am still experiencing issues saving the content to a database.
When I type inside the BlockNoteEditor and click save, it saves the entire
object iof the PartialBlock instead of the type text only.
here is an example of everything that will be saved to my database when i
type

Content string:
[{"id":"1c7410f8-9d53-4f32-ac80-56b06bbbc727","type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[{"type":"text",*"text":"texting
my project*
","styles":{}}],"children":[]},{"id":"96ab70ba-ccd7-4432-929f-b080c11b0413","type":"paragraph","props":{"textColor":"default","backgroundColor":"default","textAlignment":"left"},"content":[],"children":[]}]

the  "text",*"text":["texting my project*"] is what I actually type into
the editor but instead, it returns everything into my database.

Here below is how I set up my project.
[image: code.png]
I imported the component into my pages router and created a function to
manage Editor change
[image: handleEditor.png]
here is how i wrote the called the imported component
[image: component.png]

Kindly assist check if there's a place the mixup is coming from, please...
I honestly appreciate any observation and feedback i can get

**Comment by matthewlipski** [comment]
So if I understand correctly you want to store just the text in your database? Then you can try maybe try using `editor.blocksToMarkdownLossy(editor.document)`, which will convert the blocks to a markdown string which you can save in your database. Then you can use `editor.tryParseMarkdownToBlocks(stringFromDB)` when loading the content from your database, which will convert that string back into blocks.

However, I would recommend instead saving the blocks to a JSON string instead using `JSON.stringify(editor.document)` and restoring them with `JSON.parse(stringFromDB)`. If you only store the text instead of the full block JSON, you will lose a lot of information like block types, nesting, text/background colors, etc.

**Comment by Pokah1** [comment]
OKay,
Thank you very much for the assistance
